version: '3'
services:
  node:
    container_name: docker-node-mongo
    restart: always
    build: .
    ports:
      - '80:3000'
    depends_on:
      - "mongo"
  mongo:
    container_name: mongo
    image: "mongo"
    ports:
      - '27017:27017'